format_version: 10
environments:
  test:
    pipelines:
      - build-image
pipelines:
  build-image:
    group: default
    materials:
      app-code:
        git: https://github.com/Anurag-30/gh-action-workflows.git
        branch: main
    stages:
      - build:
          jobs:
            build-job:
              resources:
                - test
              tasks:
                - exec:
                    command: docker
                    arguments:
                      - build
                      - -t
                      - my-app:latest
                      - .
