format_version: 10
pipelines:
  build-image:
    group: default
    materials:
      app-code:
        git: https://github.com/Anurag-30/gh-action-workflows.git
    stages:
      - build:
          jobs:
            build-job:
              tasks:
                - exec:
                    command: docker
                    arguments:
                      - build
                      - -t
                      - my-app:latest
                      - .
